export const vk_infos = {
  // Mouse buttons
  0x01: {
    name: 'VK_LBUTTON',
    key: 'left',
    description: 'Left mouse button',
  },
  0x02: {
    name: 'VK_RBUTTON',
    key: 'right',
    description: 'Right mouse button',
  },
  0x03: {
    name: 'VK_CANCEL',
    key: 'cancel',
    description: 'Control-break processing',
  },
  0x04: {
    name: 'VK_MBUTTON',
    key: 'middle',
    description: 'Middle mouse button',
  },
  0x05: {
    name: 'VK_XBUTTON1',
    key: 'x1',
    description: 'X1 mouse button',
  },
  0x06: {
    name: 'VK_XBUTTON2',
    key: 'x2',
    description: 'X2 mouse button',
  },

  // Control keys
  0x08: { name: 'VK_BACK', key: 'backspace', description: 'Backspace key' },
  0x09: { name: 'VK_TAB', key: 'tab', description: 'Tab key' },
  0x0c: { name: 'VK_CLEAR', key: 'clear', description: 'Clear key' },
  0x0d: { name: 'VK_RETURN', key: 'enter', description: 'Enter key' },

  // Modifier keys
  0x10: { name: 'VK_SHIFT', key: 'shift', description: 'Shift key' },
  0x11: { name: 'VK_CONTROL', key: 'ctrl', description: 'Ctrl key' },
  0x12: { name: 'VK_MENU', key: 'alt', description: 'Alt key' },
  0x13: { name: 'VK_PAUSE', key: 'pause', description: 'Pause key' },
  0x14: { name: 'VK_CAPITAL', key: 'caps_lock', description: 'Caps Lock key' },

  // Navigation keys
  0x1b: { name: 'VK_ESCAPE', key: 'escape', description: 'Escape key' },
  0x20: { name: 'VK_SPACE', key: 'space', description: 'Spacebar' },
  0x21: { name: 'VK_PRIOR', key: 'page_up', description: 'Page Up key' },
  0x22: { name: 'VK_NEXT', key: 'page_down', description: 'Page Down key' },
  0x23: { name: 'VK_END', key: 'end', description: 'End key' },
  0x24: { name: 'VK_HOME', key: 'home', description: 'Home key' },
  0x25: { name: 'VK_LEFT', key: 'left_arrow', description: 'Left arrow key' },
  0x26: { name: 'VK_UP', key: 'up_arrow', description: 'Up arrow key' },
  0x27: {
    name: 'VK_RIGHT',
    key: 'right_arrow',
    description: 'Right arrow key',
  },
  0x28: { name: 'VK_DOWN', key: 'down_arrow', description: 'Down arrow key' },
  0x29: { name: 'VK_SELECT', key: 'select', description: 'Select key' },
  0x2a: { name: 'VK_PRINT', key: 'print', description: 'Print key' },
  0x2c: {
    name: 'VK_SNAPSHOT',
    key: 'print_screen',
    description: 'Print Screen key',
  },
  0x2d: { name: 'VK_INSERT', key: 'insert', description: 'Insert key' },
  0x2e: { name: 'VK_DELETE', key: 'delete', description: 'Delete key' },
  0x2f: { name: 'VK_HELP', key: 'help', description: 'Help key' },

  // Number keys
  0x30: { name: 'VK_0', key: '0', description: '0 key' },
  0x31: { name: 'VK_1', key: '1', description: '1 key' },
  0x32: { name: 'VK_2', key: '2', description: '2 key' },
  0x33: { name: 'VK_3', key: '3', description: '3 key' },
  0x34: { name: 'VK_4', key: '4', description: '4 key' },
  0x35: { name: 'VK_5', key: '5', description: '5 key' },
  0x36: { name: 'VK_6', key: '6', description: '6 key' },
  0x37: { name: 'VK_7', key: '7', description: '7 key' },
  0x38: { name: 'VK_8', key: '8', description: '8 key' },
  0x39: { name: 'VK_9', key: '9', description: '9 key' },

  // Letter keys
  0x41: { name: 'VK_A', key: 'a', description: 'A key' },
  0x42: { name: 'VK_B', key: 'b', description: 'B key' },
  0x43: { name: 'VK_C', key: 'c', description: 'C key' },
  0x44: { name: 'VK_D', key: 'd', description: 'D key' },
  0x45: { name: 'VK_E', key: 'e', description: 'E key' },
  0x46: { name: 'VK_F', key: 'f', description: 'F key' },
  0x47: { name: 'VK_G', key: 'g', description: 'G key' },
  0x48: { name: 'VK_H', key: 'h', description: 'H key' },
  0x49: { name: 'VK_I', key: 'i', description: 'I key' },
  0x4a: { name: 'VK_J', key: 'j', description: 'J key' },
  0x4b: { name: 'VK_K', key: 'k', description: 'K key' },
  0x4c: { name: 'VK_L', key: 'l', description: 'L key' },
  0x4d: { name: 'VK_M', key: 'm', description: 'M key' },
  0x4e: { name: 'VK_N', key: 'n', description: 'N key' },
  0x4f: { name: 'VK_O', key: 'o', description: 'O key' },
  0x50: { name: 'VK_P', key: 'p', description: 'P key' },
  0x51: { name: 'VK_Q', key: 'q', description: 'Q key' },
  0x52: { name: 'VK_R', key: 'r', description: 'R key' },
  0x53: { name: 'VK_S', key: 's', description: 'S key' },
  0x54: { name: 'VK_T', key: 't', description: 'T key' },
  0x55: { name: 'VK_U', key: 'u', description: 'U key' },
  0x56: { name: 'VK_V', key: 'v', description: 'V key' },
  0x57: { name: 'VK_W', key: 'w', description: 'W key' },
  0x58: { name: 'VK_X', key: 'x', description: 'X key' },
  0x59: { name: 'VK_Y', key: 'y', description: 'Y key' },
  0x5a: { name: 'VK_Z', key: 'z', description: 'Z key' },

  // Windows keys
  0x5b: {
    name: 'VK_LWIN',
    key: 'left_windows',
    description: 'Left Windows key',
  },
  0x5c: {
    name: 'VK_RWIN',
    key: 'right_windows',
    description: 'Right Windows key',
  },
  0x5d: {
    name: 'VK_APPS',
    key: 'applications',
    description: 'Applications key',
  },
  0x5f: { name: 'VK_SLEEP', key: 'sleep', description: 'Computer Sleep key' },

  // Numpad keys
  0x60: {
    name: 'VK_NUMPAD0',
    key: 'numpad_0',
    description: 'Numeric keypad 0 key',
  },
  0x61: {
    name: 'VK_NUMPAD1',
    key: 'numpad_1',
    description: 'Numeric keypad 1 key',
  },
  0x62: {
    name: 'VK_NUMPAD2',
    key: 'numpad_2',
    description: 'Numeric keypad 2 key',
  },
  0x63: {
    name: 'VK_NUMPAD3',
    key: 'numpad_3',
    description: 'Numeric keypad 3 key',
  },
  0x64: {
    name: 'VK_NUMPAD4',
    key: 'numpad_4',
    description: 'Numeric keypad 4 key',
  },
  0x65: {
    name: 'VK_NUMPAD5',
    key: 'numpad_5',
    description: 'Numeric keypad 5 key',
  },
  0x66: {
    name: 'VK_NUMPAD6',
    key: 'numpad_6',
    description: 'Numeric keypad 6 key',
  },
  0x67: {
    name: 'VK_NUMPAD7',
    key: 'numpad_7',
    description: 'Numeric keypad 7 key',
  },
  0x68: {
    name: 'VK_NUMPAD8',
    key: 'numpad_8',
    description: 'Numeric keypad 8 key',
  },
  0x69: {
    name: 'VK_NUMPAD9',
    key: 'numpad_9',
    description: 'Numeric keypad 9 key',
  },
  0x6a: {
    name: 'VK_MULTIPLY',
    key: 'numpad_multiply',
    description: 'Multiply key (*)',
  },
  0x6b: { name: 'VK_ADD', key: 'numpad_add', description: 'Add key (+)' },
  0x6c: {
    name: 'VK_SEPARATOR',
    key: 'separator',
    description: 'Separator key',
  },
  0x6d: {
    name: 'VK_SUBTRACT',
    key: 'numpad_subtract',
    description: 'Subtract key (-)',
  },
  0x6e: {
    name: 'VK_DECIMAL',
    key: 'numpad_decimal',
    description: 'Decimal key (.)',
  },
  0x6f: {
    name: 'VK_DIVIDE',
    key: 'numpad_divide',
    description: 'Divide key (/)',
  },

  // Function keys
  0x70: { name: 'VK_F1', key: 'f1', description: 'F1 key' },
  0x71: { name: 'VK_F2', key: 'f2', description: 'F2 key' },
  0x72: { name: 'VK_F3', key: 'f3', description: 'F3 key' },
  0x73: { name: 'VK_F4', key: 'f4', description: 'F4 key' },
  0x74: { name: 'VK_F5', key: 'f5', description: 'F5 key' },
  0x75: { name: 'VK_F6', key: 'f6', description: 'F6 key' },
  0x76: { name: 'VK_F7', key: 'f7', description: 'F7 key' },
  0x77: { name: 'VK_F8', key: 'f8', description: 'F8 key' },
  0x78: { name: 'VK_F9', key: 'f9', description: 'F9 key' },
  0x79: { name: 'VK_F10', key: 'f10', description: 'F10 key' },
  0x7a: { name: 'VK_F11', key: 'f11', description: 'F11 key' },
  0x7b: { name: 'VK_F12', key: 'f12', description: 'F12 key' },
  0x7c: { name: 'VK_F13', key: 'f13', description: 'F13 key' },
  0x7d: { name: 'VK_F14', key: 'f14', description: 'F14 key' },
  0x7e: { name: 'VK_F15', key: 'f15', description: 'F15 key' },
  0x7f: { name: 'VK_F16', key: 'f16', description: 'F16 key' },
  0x80: { name: 'VK_F17', key: 'f17', description: 'F17 key' },
  0x81: { name: 'VK_F18', key: 'f18', description: 'F18 key' },
  0x82: { name: 'VK_F19', key: 'f19', description: 'F19 key' },
  0x83: { name: 'VK_F20', key: 'f20', description: 'F20 key' },
  0x84: { name: 'VK_F21', key: 'f21', description: 'F21 key' },
  0x85: { name: 'VK_F22', key: 'f22', description: 'F22 key' },
  0x86: { name: 'VK_F23', key: 'f23', description: 'F23 key' },
  0x87: { name: 'VK_F24', key: 'f24', description: 'F24 key' },

  // Lock keys
  0x90: { name: 'VK_NUMLOCK', key: 'num_lock', description: 'Num Lock key' },
  0x91: {
    name: 'VK_SCROLL',
    key: 'scroll_lock',
    description: 'Scroll Lock key',
  },

  // Side-specific modifier keys
  0xa0: { name: 'VK_LSHIFT', key: 'left_shift', description: 'Left Shift key' },
  0xa1: {
    name: 'VK_RSHIFT',
    key: 'right_shift',
    description: 'Right Shift key',
  },
  0xa2: {
    name: 'VK_LCONTROL',
    key: 'left_ctrl',
    description: 'Left Control key',
  },
  0xa3: {
    name: 'VK_RCONTROL',
    key: 'right_ctrl',
    description: 'Right Control key',
  },
  0xa4: { name: 'VK_LMENU', key: 'left_alt', description: 'Left Alt key' },
  0xa5: { name: 'VK_RMENU', key: 'right_alt', description: 'Right Alt key' },

  // OEM and special keys
  0xba: {
    name: 'VK_OEM_1',
    key: 'semicolon',
    description: 'Semicolon key (;:) for US',
  },
  0xbb: { name: 'VK_OEM_PLUS', key: 'plus', description: 'Plus key (+)' },
  0xbc: { name: 'VK_OEM_COMMA', key: 'comma', description: 'Comma key (,)' },
  0xbd: { name: 'VK_OEM_MINUS', key: 'minus', description: 'Minus key (-)' },
  0xbe: { name: 'VK_OEM_PERIOD', key: 'period', description: 'Period key (.)' },
  0xbf: { name: 'VK_OEM_2', key: 'slash', description: 'Slash key (/?)' },
  0xc0: { name: 'VK_OEM_3', key: 'backtick', description: 'Backtick key (`~)' },
  0xdb: {
    name: 'VK_OEM_4',
    key: 'left_bracket',
    description: 'Left bracket key ([{)',
  },
  0xdc: {
    name: 'VK_OEM_5',
    key: 'backslash',
    description: 'Backslash key (\\|)',
  },
  0xdd: {
    name: 'VK_OEM_6',
    key: 'right_bracket',
    description: 'Right bracket key (]})',
  },
  0xde: { name: 'VK_OEM_7', key: 'quote', description: 'Quote key (\'")' },
  0xdf: { name: 'VK_OEM_8', key: 'oem_8', description: 'OEM specific key' },
  0xe1: { name: 'VK_OEM_AX', key: 'oem_ax', description: 'Japanese AX key' },
  0xe2: {
    name: 'VK_OEM_102',
    key: 'oem_102',
    description: 'RT 102-key keyboard key',
  },
  0xe3: { name: 'VK_ICO_HELP', key: 'ico_help', description: 'ICO Help key' },
  0xe4: { name: 'VK_ICO_00', key: 'ico_00', description: 'ICO 00 key' },
  0xe5: {
    name: 'VK_PROCESSKEY',
    key: 'process_key',
    description: 'Process key',
  },
  0xe6: {
    name: 'VK_ICO_CLEAR',
    key: 'ico_clear',
    description: 'ICO Clear key',
  },
  0xe7: {
    name: 'VK_PACKET',
    key: 'packet',
    description: 'Unicode character packet',
  },
  0xe9: {
    name: 'VK_OEM_RESET',
    key: 'oem_reset',
    description: 'OEM Reset key',
  },
  0xea: { name: 'VK_OEM_JUMP', key: 'oem_jump', description: 'OEM Jump key' },
  0xeb: { name: 'VK_OEM_PA1', key: 'oem_pa1', description: 'OEM PA1 key' },
  0xec: { name: 'VK_OEM_PA2', key: 'oem_pa2', description: 'OEM PA2 key' },
  0xed: { name: 'VK_OEM_PA3', key: 'oem_pa3', description: 'OEM PA3 key' },
  0xee: {
    name: 'VK_OEM_WSCTRL',
    key: 'oem_wsctrl',
    description: 'OEM WSCTRL key',
  },
  0xef: {
    name: 'VK_OEM_CUSEL',
    key: 'oem_cusel',
    description: 'OEM CUSEL key',
  },
  0xf0: { name: 'VK_OEM_ATTN', key: 'oem_attn', description: 'OEM ATTN key' },
  0xf1: {
    name: 'VK_OEM_FINISH',
    key: 'oem_finish',
    description: 'OEM Finish key',
  },
  0xf2: { name: 'VK_OEM_COPY', key: 'oem_copy', description: 'OEM Copy key' },
  0xf3: { name: 'VK_OEM_AUTO', key: 'oem_auto', description: 'OEM Auto key' },
  0xf4: { name: 'VK_OEM_ENLW', key: 'oem_enlw', description: 'OEM ENLW key' },
  0xf5: {
    name: 'VK_OEM_BACKTAB',
    key: 'oem_backtab',
    description: 'OEM Backtab key',
  },
  0xf6: { name: 'VK_ATTN', key: 'attn', description: 'Attn key' },
  0xf7: { name: 'VK_CRSEL', key: 'crsel', description: 'CrSel key' },
  0xf8: { name: 'VK_EXSEL', key: 'exsel', description: 'ExSel key' },
  0xf9: { name: 'VK_EREOF', key: 'ereof', description: 'Erase EOF key' },
  0xfa: { name: 'VK_PLAY', key: 'play', description: 'Play key' },
  0xfb: { name: 'VK_ZOOM', key: 'zoom', description: 'Zoom key' },
  0xfc: { name: 'VK_NONAME', key: 'noname', description: 'Reserved' },
  0xfd: { name: 'VK_PA1', key: 'pa1', description: 'PA1 key' },
  0xfe: {
    name: 'VK_OEM_CLEAR',
    key: 'oem_clear',
    description: 'OEM Clear key',
  },
} as const
