export interface KeyDef {
   scan: number
   extended?: boolean
}

export const KEYBOARD_MAPPING: Record<string, KeyDef> = {
   a: { scan: 0x1e },
   b: { scan: 0x30 },
   c: { scan: 0x2e },
   d: { scan: 0x20 },
   e: { scan: 0x12 },
   f: { scan: 0x21 },
   g: { scan: 0x22 },
   h: { scan: 0x23 },
   i: { scan: 0x17 },
   j: { scan: 0x24 },
   k: { scan: 0x25 },
   l: { scan: 0x26 },
   m: { scan: 0x32 },
   n: { scan: 0x31 },
   o: { scan: 0x18 },
   p: { scan: 0x19 },
   q: { scan: 0x10 },
   r: { scan: 0x13 },
   s: { scan: 0x1f },
   t: { scan: 0x14 },
   u: { scan: 0x16 },
   v: { scan: 0x2f },
   w: { scan: 0x11 },
   x: { scan: 0x2d },
   y: { scan: 0x15 },
   z: { scan: 0x2c },

   // Numbers
   '0': { scan: 0x0b },
   '1': { scan: 0x02 },
   '2': { scan: 0x03 },
   '3': { scan: 0x04 },
   '4': { scan: 0x05 },
   '5': { scan: 0x06 },
   '6': { scan: 0x07 },
   '7': { scan: 0x08 },
   '8': { scan: 0x09 },
   '9': { scan: 0x0a },

   // Special keys
   enter: { scan: 0x1c },
   numEnter: { scan: 0x1c, extended: true },
   space: { scan: 0x39 },
   tab: { scan: 0x0f },
   escape: { scan: 0x01 },
   backspace: { scan: 0x0e },
   capslock: { scan: 0x3a },
   shift: { scan: 0x2a },
   ctrl: { scan: 0x1d },
   rctrl: { scan: 0x1d, extended: true },
   alt: { scan: 0x38 },
   ralt: { scan: 0x38, extended: true },

   up: { scan: 0x48, extended: true },
   down: { scan: 0x50, extended: true },
   left: { scan: 0x4b, extended: true },
   right: { scan: 0x4d, extended: true },

   insert: { scan: 0x52, extended: true },
   delete: { scan: 0x53, extended: true },
   home: { scan: 0x47, extended: true },
   end: { scan: 0x4f, extended: true },
   pageup: { scan: 0x49, extended: true },
   pagedown: { scan: 0x51, extended: true },

   f1: { scan: 0x3b },
   f2: { scan: 0x3c },
   f3: { scan: 0x3d },
   f4: { scan: 0x3e },
   f5: { scan: 0x3f },
   f6: { scan: 0x40 },
   f7: { scan: 0x41 },
   f8: { scan: 0x42 },
   f9: { scan: 0x43 },
   f10: { scan: 0x44 },
   f11: { scan: 0x57 },
   f12: { scan: 0x58 },
}

export const SHIFT_KEYS = new Map<string, string>([
   ['!', '1'],
   ['@', '2'],
   ['#', '3'],
   ['$', '4'],
   ['%', '5'],
   ['^', '6'],
   ['&', '7'],
   ['*', '8'],
   ['(', '9'],
   [')', '0'],
   ['_', '-'],
   ['+', '='],
   ['{', '['],
   ['}', ']'],
   ['|', '\\'],
   [':', ';'],
   ['"', "'"],
   ['<', ','],
   ['>', '.'],
   ['?', '/'],
   ['~', '`'],
])
