export interface KeyDef {
  scan: number;
  extended?: boolean;
  vk?: number;
}

export const VK_CODES = {
  LBUTTON: 0x01,
  RBUTTON: 0x02,
  MBUTTON: 0x04,
  XBUTTON1: 0x05,
  XBUTTON2: 0x06,

  BACK: 0x08,
  TAB: 0x09,
  RETURN: 0x0d,
  SHIFT: 0x10,
  CONTROL: 0x11,
  MENU: 0x12,
  PAUSE: 0x13,
  CAPITAL: 0x14,
  ESCAPE: 0x1b,
  SPACE: 0x20,
  PRIOR: 0x21,
  NEXT: 0x22,
  END: 0x23,
  HOME: 0x24,
  LEFT: 0x25,
  UP: 0x26,
  RIGHT: 0x27,
  DOWN: 0x28,
  INSERT: 0x2d,
  DELETE: 0x2e,

  KEY_0: 0x30,
  KEY_1: 0x31,
  KEY_2: 0x32,
  KEY_3: 0x33,
  KEY_4: 0x34,
  KEY_5: 0x35,
  KEY_6: 0x36,
  KEY_7: 0x37,
  KEY_8: 0x38,
  KEY_9: 0x39,

  KEY_A: 0x41,
  KEY_B: 0x42,
  KEY_C: 0x43,
  KEY_D: 0x44,
  KEY_E: 0x45,
  KEY_F: 0x46,
  KEY_G: 0x47,
  KEY_H: 0x48,
  KEY_I: 0x49,
  KEY_J: 0x4a,
  KEY_K: 0x4b,
  KEY_L: 0x4c,
  KEY_M: 0x4d,
  KEY_N: 0x4e,
  KEY_O: 0x4f,
  KEY_P: 0x50,
  KEY_Q: 0x51,
  KEY_R: 0x52,
  KEY_S: 0x53,
  KEY_T: 0x54,
  KEY_U: 0x55,
  KEY_V: 0x56,
  KEY_W: 0x57,
  KEY_X: 0x58,
  KEY_Y: 0x59,
  KEY_Z: 0x5a,

  LWIN: 0x5b,
  RWIN: 0x5c,
  APPS: 0x5d,

  NUMPAD0: 0x60,
  NUMPAD1: 0x61,
  NUMPAD2: 0x62,
  NUMPAD3: 0x63,
  NUMPAD4: 0x64,
  NUMPAD5: 0x65,
  NUMPAD6: 0x66,
  NUMPAD7: 0x67,
  NUMPAD8: 0x68,
  NUMPAD9: 0x69,
  MULTIPLY: 0x6a,
  ADD: 0x6b,
  SEPARATOR: 0x6c,
  SUBTRACT: 0x6d,
  DECIMAL: 0x6e,
  DIVIDE: 0x6f,

  F1: 0x70,
  F2: 0x71,
  F3: 0x72,
  F4: 0x73,
  F5: 0x74,
  F6: 0x75,
  F7: 0x76,
  F8: 0x77,
  F9: 0x78,
  F10: 0x79,
  F11: 0x7a,
  F12: 0x7b,
  F13: 0x7c,
  F14: 0x7d,
  F15: 0x7e,
  F16: 0x7f,
  F17: 0x80,
  F18: 0x81,
  F19: 0x82,
  F20: 0x83,
  F21: 0x84,
  F22: 0x85,
  F23: 0x86,
  F24: 0x87,

  NUMLOCK: 0x90,
  SCROLL: 0x91,

  LSHIFT: 0xa0,
  RSHIFT: 0xa1,
  LCONTROL: 0xa2,
  RCONTROL: 0xa3,
  LMENU: 0xa4,
  RMENU: 0xa5,

  BROWSER_BACK: 0xa6,
  BROWSER_FORWARD: 0xa7,
  BROWSER_REFRESH: 0xa8,
  BROWSER_STOP: 0xa9,
  BROWSER_SEARCH: 0xaa,
  BROWSER_FAVORITES: 0xab,
  BROWSER_HOME: 0xac,

  VOLUME_MUTE: 0xad,
  VOLUME_DOWN: 0xae,
  VOLUME_UP: 0xaf,
  MEDIA_NEXT_TRACK: 0xb0,
  MEDIA_PREV_TRACK: 0xb1,
  MEDIA_STOP: 0xb2,
  MEDIA_PLAY_PAUSE: 0xb3,

  LAUNCH_MAIL: 0xb4,
  LAUNCH_MEDIA_SELECT: 0xb5,
  LAUNCH_APP1: 0xb6,
  LAUNCH_APP2: 0xb7,

  OEM_1: 0xba,
  OEM_PLUS: 0xbb,
  OEM_COMMA: 0xbc,
  OEM_MINUS: 0xbd,
  OEM_PERIOD: 0xbe,
  OEM_2: 0xbf,
  OEM_3: 0xc0,
  OEM_4: 0xdb,
  OEM_5: 0xdc,
  OEM_6: 0xdd,
  OEM_7: 0xde,

  SNAPSHOT: 0x2c,
  SLEEP: 0x5f,
} as const;

export const KEYBOARD_MAPPING = {
  a: { scan: 0x1e, vk: VK_CODES.KEY_A },
  b: { scan: 0x30, vk: VK_CODES.KEY_B },
  c: { scan: 0x2e, vk: VK_CODES.KEY_C },
  d: { scan: 0x20, vk: VK_CODES.KEY_D },
  e: { scan: 0x12, vk: VK_CODES.KEY_E },
  f: { scan: 0x21, vk: VK_CODES.KEY_F },
  g: { scan: 0x22, vk: VK_CODES.KEY_G },
  h: { scan: 0x23, vk: VK_CODES.KEY_H },
  i: { scan: 0x17, vk: VK_CODES.KEY_I },
  j: { scan: 0x24, vk: VK_CODES.KEY_J },
  k: { scan: 0x25, vk: VK_CODES.KEY_K },
  l: { scan: 0x26, vk: VK_CODES.KEY_L },
  m: { scan: 0x32, vk: VK_CODES.KEY_M },
  n: { scan: 0x31, vk: VK_CODES.KEY_N },
  o: { scan: 0x18, vk: VK_CODES.KEY_O },
  p: { scan: 0x19, vk: VK_CODES.KEY_P },
  q: { scan: 0x10, vk: VK_CODES.KEY_Q },
  r: { scan: 0x13, vk: VK_CODES.KEY_R },
  s: { scan: 0x1f, vk: VK_CODES.KEY_S },
  t: { scan: 0x14, vk: VK_CODES.KEY_T },
  u: { scan: 0x16, vk: VK_CODES.KEY_U },
  v: { scan: 0x2f, vk: VK_CODES.KEY_V },
  w: { scan: 0x11, vk: VK_CODES.KEY_W },
  x: { scan: 0x2d, vk: VK_CODES.KEY_X },
  y: { scan: 0x15, vk: VK_CODES.KEY_Y },
  z: { scan: 0x2c, vk: VK_CODES.KEY_Z },

  "0": { scan: 0x0b, vk: VK_CODES.KEY_0 },
  "1": { scan: 0x02, vk: VK_CODES.KEY_1 },
  "2": { scan: 0x03, vk: VK_CODES.KEY_2 },
  "3": { scan: 0x04, vk: VK_CODES.KEY_3 },
  "4": { scan: 0x05, vk: VK_CODES.KEY_4 },
  "5": { scan: 0x06, vk: VK_CODES.KEY_5 },
  "6": { scan: 0x07, vk: VK_CODES.KEY_6 },
  "7": { scan: 0x08, vk: VK_CODES.KEY_7 },
  "8": { scan: 0x09, vk: VK_CODES.KEY_8 },
  "9": { scan: 0x0a, vk: VK_CODES.KEY_9 },

  f1: { scan: 0x3b, vk: VK_CODES.F1 },
  f2: { scan: 0x3c, vk: VK_CODES.F2 },
  f3: { scan: 0x3d, vk: VK_CODES.F3 },
  f4: { scan: 0x3e, vk: VK_CODES.F4 },
  f5: { scan: 0x3f, vk: VK_CODES.F5 },
  f6: { scan: 0x40, vk: VK_CODES.F6 },
  f7: { scan: 0x41, vk: VK_CODES.F7 },
  f8: { scan: 0x42, vk: VK_CODES.F8 },
  f9: { scan: 0x43, vk: VK_CODES.F9 },
  f10: { scan: 0x44, vk: VK_CODES.F10 },
  f11: { scan: 0x57, vk: VK_CODES.F11 },
  f12: { scan: 0x58, vk: VK_CODES.F12 },
  f13: { scan: 0x64, vk: VK_CODES.F13 },
  f14: { scan: 0x65, vk: VK_CODES.F14 },
  f15: { scan: 0x66, vk: VK_CODES.F15 },
  f16: { scan: 0x67, vk: VK_CODES.F16 },
  f17: { scan: 0x68, vk: VK_CODES.F17 },
  f18: { scan: 0x69, vk: VK_CODES.F18 },
  f19: { scan: 0x6a, vk: VK_CODES.F19 },
  f20: { scan: 0x6b, vk: VK_CODES.F20 },
  f21: { scan: 0x6c, vk: VK_CODES.F21 },
  f22: { scan: 0x6d, vk: VK_CODES.F22 },
  f23: { scan: 0x6e, vk: VK_CODES.F23 },
  f24: { scan: 0x76, vk: VK_CODES.F24 },

  "-": { scan: 0x0c, vk: VK_CODES.OEM_MINUS },
  minus: { scan: 0x0c, vk: VK_CODES.OEM_MINUS },
  "=": { scan: 0x0d, vk: VK_CODES.OEM_PLUS },
  equal: { scan: 0x0d, vk: VK_CODES.OEM_PLUS },
  equals: { scan: 0x0d, vk: VK_CODES.OEM_PLUS },
  "[": { scan: 0x1a, vk: VK_CODES.OEM_4 },
  bracketleft: { scan: 0x1a, vk: VK_CODES.OEM_4 },
  "]": { scan: 0x1b, vk: VK_CODES.OEM_6 },
  bracketright: { scan: 0x1b, vk: VK_CODES.OEM_6 },
  "\\": { scan: 0x2b, vk: VK_CODES.OEM_5 },
  backslash: { scan: 0x2b, vk: VK_CODES.OEM_5 },
  ";": { scan: 0x27, vk: VK_CODES.OEM_1 },
  semicolon: { scan: 0x27, vk: VK_CODES.OEM_1 },
  "'": { scan: 0x28, vk: VK_CODES.OEM_7 },
  quote: { scan: 0x28, vk: VK_CODES.OEM_7 },
  apostrophe: { scan: 0x28, vk: VK_CODES.OEM_7 },
  "`": { scan: 0x29, vk: VK_CODES.OEM_3 },
  grave: { scan: 0x29, vk: VK_CODES.OEM_3 },
  backtick: { scan: 0x29, vk: VK_CODES.OEM_3 },
  ",": { scan: 0x33, vk: VK_CODES.OEM_COMMA },
  comma: { scan: 0x33, vk: VK_CODES.OEM_COMMA },
  ".": { scan: 0x34, vk: VK_CODES.OEM_PERIOD },
  period: { scan: 0x34, vk: VK_CODES.OEM_PERIOD },
  dot: { scan: 0x34, vk: VK_CODES.OEM_PERIOD },
  "/": { scan: 0x35, vk: VK_CODES.OEM_2 },
  slash: { scan: 0x35, vk: VK_CODES.OEM_2 },
  forwardslash: { scan: 0x35, vk: VK_CODES.OEM_2 },

  space: { scan: 0x39, vk: VK_CODES.SPACE },
  enter: { scan: 0x1c, vk: VK_CODES.RETURN },
  return: { scan: 0x1c, vk: VK_CODES.RETURN },
  tab: { scan: 0x0f, vk: VK_CODES.TAB },
  backspace: { scan: 0x0e, vk: VK_CODES.BACK },
  escape: { scan: 0x01, vk: VK_CODES.ESCAPE },
  esc: { scan: 0x01, vk: VK_CODES.ESCAPE },

  shift: { scan: 0x2a, vk: VK_CODES.SHIFT },
  shiftleft: { scan: 0x2a, vk: VK_CODES.LSHIFT },
  shiftright: { scan: 0x36, vk: VK_CODES.RSHIFT },
  ctrl: { scan: 0x1d, vk: VK_CODES.CONTROL },
  control: { scan: 0x1d, vk: VK_CODES.CONTROL },
  ctrlleft: { scan: 0x1d, vk: VK_CODES.LCONTROL },
  controlleft: { scan: 0x1d, vk: VK_CODES.LCONTROL },
  ctrlright: { scan: 0x1d, extended: true, vk: VK_CODES.RCONTROL },
  controlright: { scan: 0x1d, extended: true, vk: VK_CODES.RCONTROL },
  rctrl: { scan: 0x1d, extended: true, vk: VK_CODES.RCONTROL },
  alt: { scan: 0x38, vk: VK_CODES.MENU },
  altleft: { scan: 0x38, vk: VK_CODES.LMENU },
  altright: { scan: 0x38, extended: true, vk: VK_CODES.RMENU },
  ralt: { scan: 0x38, extended: true, vk: VK_CODES.RMENU },
  altgr: { scan: 0x38, extended: true, vk: VK_CODES.RMENU },
  win: { scan: 0x5b, extended: true, vk: VK_CODES.LWIN },
  winleft: { scan: 0x5b, extended: true, vk: VK_CODES.LWIN },
  windows: { scan: 0x5b, extended: true, vk: VK_CODES.LWIN },
  winright: { scan: 0x5c, extended: true, vk: VK_CODES.RWIN },
  windowsright: { scan: 0x5c, extended: true, vk: VK_CODES.RWIN },
  apps: { scan: 0x5d, extended: true, vk: VK_CODES.APPS },
  menu: { scan: 0x5d, extended: true, vk: VK_CODES.APPS },
  contextmenu: { scan: 0x5d, extended: true, vk: VK_CODES.APPS },

  capslock: { scan: 0x3a, vk: VK_CODES.CAPITAL },
  numlock: { scan: 0x45, vk: VK_CODES.NUMLOCK },
  scrolllock: { scan: 0x46, vk: VK_CODES.SCROLL },

  up: { scan: 0x48, extended: true, vk: VK_CODES.UP },
  down: { scan: 0x50, extended: true, vk: VK_CODES.DOWN },
  left: { scan: 0x4b, extended: true, vk: VK_CODES.LEFT },
  right: { scan: 0x4d, extended: true, vk: VK_CODES.RIGHT },
  home: { scan: 0x47, extended: true, vk: VK_CODES.HOME },
  end: { scan: 0x4f, extended: true, vk: VK_CODES.END },
  pageup: { scan: 0x49, extended: true, vk: VK_CODES.PRIOR },
  pagedown: { scan: 0x51, extended: true, vk: VK_CODES.NEXT },
  insert: { scan: 0x52, extended: true, vk: VK_CODES.INSERT },
  delete: { scan: 0x53, extended: true, vk: VK_CODES.DELETE },
  del: { scan: 0x53, extended: true, vk: VK_CODES.DELETE },

  numpad0: { scan: 0x52, vk: VK_CODES.NUMPAD0 },
  numpad1: { scan: 0x4f, vk: VK_CODES.NUMPAD1 },
  numpad2: { scan: 0x50, vk: VK_CODES.NUMPAD2 },
  numpad3: { scan: 0x51, vk: VK_CODES.NUMPAD3 },
  numpad4: { scan: 0x4b, vk: VK_CODES.NUMPAD4 },
  numpad5: { scan: 0x4c, vk: VK_CODES.NUMPAD5 },
  numpad6: { scan: 0x4d, vk: VK_CODES.NUMPAD6 },
  numpad7: { scan: 0x47, vk: VK_CODES.NUMPAD7 },
  numpad8: { scan: 0x48, vk: VK_CODES.NUMPAD8 },
  numpad9: { scan: 0x49, vk: VK_CODES.NUMPAD9 },
  numpaddecimal: { scan: 0x53, vk: VK_CODES.DECIMAL },
  numpadperiod: { scan: 0x53, vk: VK_CODES.DECIMAL },
  numpaddivide: { scan: 0x35, extended: true, vk: VK_CODES.DIVIDE },
  numpadmultiply: { scan: 0x37, vk: VK_CODES.MULTIPLY },
  numpadsubtract: { scan: 0x4a, vk: VK_CODES.SUBTRACT },
  numpadadd: { scan: 0x4e, vk: VK_CODES.ADD },
  numpadenter: { scan: 0x1c, extended: true, vk: VK_CODES.RETURN },

  num0: { scan: 0x52, vk: VK_CODES.NUMPAD0 },
  num1: { scan: 0x4f, vk: VK_CODES.NUMPAD1 },
  num2: { scan: 0x50, vk: VK_CODES.NUMPAD2 },
  num3: { scan: 0x51, vk: VK_CODES.NUMPAD3 },
  num4: { scan: 0x4b, vk: VK_CODES.NUMPAD4 },
  num5: { scan: 0x4c, vk: VK_CODES.NUMPAD5 },
  num6: { scan: 0x4d, vk: VK_CODES.NUMPAD6 },
  num7: { scan: 0x47, vk: VK_CODES.NUMPAD7 },
  num8: { scan: 0x48, vk: VK_CODES.NUMPAD8 },
  num9: { scan: 0x49, vk: VK_CODES.NUMPAD9 },

  volumeup: { scan: 0, vk: VK_CODES.VOLUME_UP },
  volumedown: { scan: 0, vk: VK_CODES.VOLUME_DOWN },
  volumemute: { scan: 0, vk: VK_CODES.VOLUME_MUTE },
  mute: { scan: 0, vk: VK_CODES.VOLUME_MUTE },
  playpause: { scan: 0, vk: VK_CODES.MEDIA_PLAY_PAUSE },
  stop: { scan: 0, vk: VK_CODES.MEDIA_STOP },
  nexttrack: { scan: 0, vk: VK_CODES.MEDIA_NEXT_TRACK },
  previoustrack: { scan: 0, vk: VK_CODES.MEDIA_PREV_TRACK },
  medianext: { scan: 0, vk: VK_CODES.MEDIA_NEXT_TRACK },
  mediaprevious: { scan: 0, vk: VK_CODES.MEDIA_PREV_TRACK },
  mediaplaypause: { scan: 0, vk: VK_CODES.MEDIA_PLAY_PAUSE },
  mediastop: { scan: 0, vk: VK_CODES.MEDIA_STOP },

  browserhome: { scan: 0, vk: VK_CODES.BROWSER_HOME },
  browserback: { scan: 0, vk: VK_CODES.BROWSER_BACK },
  browserforward: { scan: 0, vk: VK_CODES.BROWSER_FORWARD },
  browserrefresh: { scan: 0, vk: VK_CODES.BROWSER_REFRESH },
  browserstop: { scan: 0, vk: VK_CODES.BROWSER_STOP },
  browsersearch: { scan: 0, vk: VK_CODES.BROWSER_SEARCH },
  browserfavorites: { scan: 0, vk: VK_CODES.BROWSER_FAVORITES },

  mail: { scan: 0, vk: VK_CODES.LAUNCH_MAIL },
  calculator: { scan: 0, vk: VK_CODES.LAUNCH_APP2 },
  mycomputer: { scan: 0, vk: VK_CODES.LAUNCH_APP1 },
  computer: { scan: 0, vk: VK_CODES.LAUNCH_APP1 },

  printscreen: { scan: 0x37, extended: true, vk: VK_CODES.SNAPSHOT },
  prtsc: { scan: 0x37, extended: true, vk: VK_CODES.SNAPSHOT },
  pause: { scan: 0x45, vk: VK_CODES.PAUSE },
  break: { scan: 0x46, vk: VK_CODES.PAUSE },

  sleep: { scan: 0, vk: VK_CODES.SLEEP },

  intl1: { scan: 0x73 },
  intl2: { scan: 0x70 },
  intl3: { scan: 0x7d },
  intl4: { scan: 0x79 },
  intl5: { scan: 0x7b },
  intl6: { scan: 0x5c },
  lang1: { scan: 0x72 },
  lang2: { scan: 0x71 },
} as const;

export type KeyName = keyof typeof KEYBOARD_MAPPING;

export const SHIFT_KEYS = new Map<string, string>([
  ["!", "1"],
  ["@", "2"],
  ["#", "3"],
  ["$", "4"],
  ["%", "5"],
  ["^", "6"],
  ["&", "7"],
  ["*", "8"],
  ["(", "9"],
  [")", "0"],

  ["_", "-"],
  ["+", "="],
  ["{", "["],
  ["}", "]"],
  ["|", "\\"],
  [":", ";"],
  ['"', "'"],
  ["<", ","],
  [">", "."],
  ["?", "/"],
  ["~", "`"],
]);

type KeyDefWithOptional = { scan: number; vk?: number; extended?: boolean };

export const VK_TO_KEYNAME: Record<number, KeyName> = {};
for (const [name, def] of Object.entries(KEYBOARD_MAPPING)) {
  const keyDef = def as KeyDefWithOptional;
  if (keyDef.vk && !VK_TO_KEYNAME[keyDef.vk]) {
    VK_TO_KEYNAME[keyDef.vk] = name as KeyName;
  }
}

export const SCAN_TO_KEYNAME: Record<number, KeyName> = {};
export const EXTENDED_SCAN_TO_KEYNAME: Record<number, KeyName> = {};
for (const [name, def] of Object.entries(KEYBOARD_MAPPING)) {
  const keyDef = def as KeyDefWithOptional;
  if (keyDef.scan > 0) {
    if (keyDef.extended) {
      if (!EXTENDED_SCAN_TO_KEYNAME[keyDef.scan]) {
        EXTENDED_SCAN_TO_KEYNAME[keyDef.scan] = name as KeyName;
      }
    } else {
      if (!SCAN_TO_KEYNAME[keyDef.scan]) {
        SCAN_TO_KEYNAME[keyDef.scan] = name as KeyName;
      }
    }
  }
}
