// Mouse Event Flags
export const MOUSEEVENTF_MOVE = 0x0001
export const MOUSEEVENTF_ABSOLUTE = 0x8000
export const MOUSEEVENTF_LEFTDOWN = 0x0002
export const MOUSEEVENTF_LEFTUP = 0x0004
export const MOUSEEVENTF_LEFTCLICK = MOUSEEVENTF_LEFTDOWN + MOUSEEVENTF_LEFTUP
export const MOUSEEVENTF_RIGHTDOWN = 0x0008
export const MOUSEEVENTF_RIGHTUP = 0x0010
export const MOUSEEVENTF_RIGHTCLICK =
  MOUSEEVENTF_RIGHTDOWN + MOUSEEVENTF_RIGHTUP
export const MOUSEEVENTF_MIDDLEDOWN = 0x0020
export const MOUSEEVENTF_MIDDLEUP = 0x0040
export const MOUSEEVENTF_MIDDLECLICK =
  MOUSEEVENTF_MIDDLEDOWN + MOUSEEVENTF_MIDDLEUP
export const MOUSEEVENTF_XDOWN = 0x0080
export const MOUSEEVENTF_XUP = 0x0100

// Mouse data for X buttons
export const XBUTTON1 = 0x0001
export const XBUTTON2 = 0x0002

// KeyBdInput Flags
export const KEYEVENTF_EXTENDEDKEY = 0x0001
export const KEYEVENTF_KEYUP = 0x0002
export const KEYEVENTF_SCANCODE = 0x0008
export const KEYEVENTF_UNICODE = 0x0004

// MapVirtualKey Map Types
export const MAPVK_VK_TO_CHAR = 2
export const MAPVK_VK_TO_VSC = 0
export const MAPVK_VSC_TO_VK = 1
export const MAPVK_VSC_TO_VK_EX = 3
